dependencies:
    picard: ./picard.jar
    fgbio: ./fgbio-2.0.1.jar
    bwa: bwa
    sambamba: sambamba
    samtools: samtools
    fastp: ./fastp
reference: dmel6
read_structure_r1: 5M2S144T
read_structure_r2: 5M2S144T
